var locationsListController =  function ($scope) {
    $scope.locations = [   
        { LocationCode: "ABP", LocationName: "Albany Park", LocationNamePrefix: "New Life", LocationPhoneNumber: 7733837099, LocationEmail: "albanypark@newlifechicago.org", LocationAddress1: "3542 W Sunnyside", LocationCity: "Chicago",  LocationState: "IL", LocationZip: 60625, PastorBio: "Joshua Sherif is an Egyptian born Pastor serving with New Life Community Church in Chicago. Pastor Joshua serves as the Lead Pastor for the Albany Park Location, one of the most diverse neighborhoods in America. Pastor Joshua has a heart to share the gospel with those who have not had an opportunity to hear it and to equip others to do the same. Pastor Joshua and his wife Gina live on the North Side of Chicago and are excited to be a part of the New Life team.", LocationPastorName: "Pastor Joshua & Gina Sherif", LocationServiceHours: "English 11:00am"},
        { LocationCode: "AOP", LocationName: "Austin-Oak Park", LocationNamePrefix: "New Life", LocationPhoneNumber: 7734179881, LocationEmail: "austin-oakpark@newlifechicago.org", LocationAddress1: "200 N Oak Park Ave", LocationCity: "Oak Park",  LocationState: "IL", LocationZip: 60302, PastorBio: "Gerald W. Smith was born in Utica, NY to God-fearing parents who guided him to salvation at the age of six. Happily married to Dorean, blessed with two children and 3 grandchildren. He received a degree in Youth ministry from Liberty University, trained as a Nuethetic counselor with Biblical Counseling Center and graduated from Devos Urban Leadership in 2003. He is a fourth generation pastor who served as a licensed and ordained pastor for 20 years. Those twenty years have been with a two new church plants in Chicago and Richmond, Va.", LocationPastorName: "Pastor Gerald and Dorean Smith", LocationServiceHours: "English 10:00am"},
        { LocationCode: "BRW", LocationName: "Berwyn", LocationNamePrefix: "New Life", LocationPhoneNumber: 7085726490, LocationEmail: "berwyn@newlifechicago.org", LocationAddress1: "1900 Oak Park Avenue", LocationCity: "Berwyn",  LocationState: "IL", LocationZip: 60402, PastorBio: "Born and raised on the South Side of Chicago, Abiathar Carroll is a fourth generation Minister of The Gospel. He and his wife Nereida have five adult children and eight grandchildren. He is a Disabled Viet Nam veteran. He was ordained to preach the Gospel of Jesus Christ in 1978. Pastor Abiathar worked for AT&T for 25 years and has owned several businesses. Abiathar¹s education includes Electrical Engineering, Business Management and other areas. Abiathar and his wife have served together in many ministries and have been at New Life since 2006.", LocationPastorName: "Pastor Abiathar & Nerieda Carroll", LocationServiceHours: "Sun. English 11:30am;"},
        { LocationCode: "BPT", LocationName: "Bridgeport", LocationNamePrefix: "New Life", LocationPhoneNumber: 3128421470, LocationEmail: "bridgeport@newlifechicago.org", LocationAddress1: "3039 S. Normal Ave.", LocationCity: "Chicago",  LocationState: "IL", LocationZip: 60616, PastorBio: "Luke Dudenhofer was raised in Stanton, Michigan, where his father served as a pastor. He came to Chicago to study at Moody Bible Institute and graduated in 1999. Luke ministered through teaching for three years. In 2002 Pastor Luke helped lead the launch of New Life Bridgeport. He and his wife Melissa have been married since 1998, find joy in raising their three children, and are excited to be part of God's mission of reconciliation in the Main community.", LocationPastorName: "Pastor Luke & Melissa Dudenhofer", LocationServiceHours: "English 10:00am"},
        { LocationCode: "BRP", LocationName: "Brighton Park", LocationNamePrefix: "New Life", LocationPhoneNumber: 7737620270, LocationEmail: "brightonpark@newlifechicago.org", LocationAddress1: "4155 S. Rockwell St.", LocationCity: "Chicago",  LocationState: "IL", LocationZip: 60632, PastorBio: "Eduardo was born in Durango, Mexico and has lived in Chicago since he was seven years old. His parents gave their lives to Christ while they lived in Mexico which made it possible for Eduardo to be raised in a christian home. At the age of 12 he decided take the step of baptism. Together with his wife Lupita they responded to the call to serve in the Brighton Park community since April of 2009 and in June of 2010 they were called to pastor Nueva Vida Brighton Park. Eduardo and Lupita have been married for 14 years and are the proud parents of Natali and Daniel.", LocationPastorName: "Pastor Eduardo and Lupita Huerta", LocationServiceHours: "English 9:30am; Spanish 11:30am"},
        { LocationCode: "BKF", LocationName: "Brookfield", LocationNamePrefix: "New Life", LocationPhoneNumber: 7082779191, LocationEmail: "brookfield@newlifechicago.org", LocationAddress1: "9311 Shields Avenue", LocationCity: "Brookfield", LocationState: "IL", LocationZip: 60513, PastorBio: "Pastor Chris comes to New Life after more than seven years of pastoral youth ministry in Hudsonville, MI. Chris and Kristi have been married since 1996 and have four kids. Chris and Kristi both grew up in West Michigan and have a love for the outdoors, photography and family adventures. Their kids love taking the train into the city, the Brookfield Zoo, and the variety of restaurants in Chicagoland. After over 25 years in the same church, Chris felt that God was calling his family to a new work in Chicago. The Rookus' moved to Brookfield in June of 2014 and are excited to be a part of a movement city proclaiming the good news of Jesus Christ.", LocationPastorName: "Pastor Chris and Kristi Rookus", LocationServiceHours: "English 10:00am" },
        { LocationCode: "CRO", LocationName: "Cicero", LocationNamePrefix: "New Life", LocationPhoneNumber: 7087805433, LocationEmail: "cicero@newlifechicago.org", LocationAddress1: "3601 S. 61st Ave.", LocationCity: "Cicero",  LocationState: "IL", LocationZip: 60804, PastorBio: "Tony Wasso is a native of Chicago¹s Maxwell Street area. Through the influence of his wife Linda, Tony began investigating the things of God and soon found himself making a decision to serve God. Tony and Linda have been a part of New Life for many years now and have served in many capacities and lead various ministries. In 1999 Pastor Tony launched the New Life congregation in Cicero. Pastor Tony is known for his shepherds heart and deep desire to see Gods people healed and whole spiritually. Tony¹s wife Linda serves as administrative assistant to Pastor Mark Jobe.", LocationPastorName: "Pastor Tony & Linda Wasso", LocationServiceHours: "English 11:00am; Spanish 11:00am"},
        { LocationCode: "HBP", LocationName: "Humboldt Park", LocationNamePrefix: "New Life", LocationPhoneNumber: 7732521104, LocationEmail: "humboldtpark@newlifechicago.org", LocationAddress1: "1410 N. Springfield Ave.", LocationCity: "Chicago",  LocationState: "IL", LocationZip: 60651, PastorBio: "In 2003, John LaTorre was radically delivered from the bondage of addiction and given a restart at a new life through Jesus Christ. Upon his deliverance, In 2006, he moved to Chicago to attend Moody Bible Institute, received his degree in 2010 and is currently studying for his Masters of Ministry degree. He was married in 2009 to his partner and best friend Bethany. Johnny B has served in the Humboldt Park neighborhood since 2009. In January 2012, John assumed the role of lead pastor for the English congregation at New Life Humboldt Park.", LocationPastorName: "Pastor John & Bethany LaTorre", LocationServiceHours: "Spanish 9:30am; English Noon"},
        { LocationCode: "LNP", LocationName: "Lincoln Park", LocationNamePrefix: "New Life", LocationPhoneNumber: 7733489049, LocationEmail: "lincolnpark@newlifechicago.org", LocationAddress1: "1110 W. Lill Ave.", LocationCity: "Chicago",  LocationState: "IL", LocationZip: 60614, PastorBio: "At 16, Bobby made the decision to serve God in full time ministry. Growing up in Northwest Indiana, Bobby received his BA in Youth Ministry at Moody Bible Institute, a BA in Psychology from Governors State University and a MA in Biblical Exegesis from Wheaton Grad School. Pastor Bobby is an adjunct Professor at Moody Bible Institute and Lead Pastor at New Life Lincoln Park. His absolute favorite thing to do is spend time with his wife Jeannette, daughter Baylee Eden and son Jaxon Zion. ", LocationPastorName: "Pastor Bobby Moss", LocationServiceHours: "9:00am, 11:00am & 4:30pm"},
        { LocationCode: "LVL", LocationName: "Little Village-Lawndale", LocationNamePrefix: "New Life", LocationPhoneNumber: 7737620270, LocationEmail: "littlevillage@newlifechicago.org", LocationAddress1: "2657 S. Lawndale Ave.", LocationCity: "Chicago",  LocationState: "IL", LocationZip: 60623, PastorBio: "Pastor Francisco \"Paco\" Amador was born in Mexico City. At the age of 14 he gave his life to the King. Following a desire to serve Him, Paco came to Chicago and the Moody Bible Institute. In 1990 he visited the Little Village neighborhood and fell in love with the community. A few years later he moved in to the neighborhood. Pastor Paco has served as a missionary in Spain, worked at Lawndale Christian Health Center and taught elementary school. In 2005 he was called into full time ministry as the pastor at New Life Little Village. Paco loves running with his wife, dancing with his daughters and wrestling with his boys. Pastor Paco & Sylvia have have 7 children.", LocationPastorName: "Pastor Francisco & Sylvia Amador", LocationServiceHours: "Spanish 10:00am; English Noon"},
        { LocationCode: "LVK", LocationName: "Little Village-Karlov", LocationNamePrefix: "New Life", LocationPhoneNumber: 7737620270, LocationEmail: "karlov@newlifechicago.org", LocationAddress1: "4106 W 28th Street", LocationCity: "Chicago",  LocationState: "IL", LocationZip: 60623, PastorBio: "Chris began to seriously follow the Lord when he was 18 years old at Palatine High School in Palatine, IL. Chris felt called to understand his new beliefs and entered Biblical Studies at Trinity International University. Chris married Krista and the two felt called to move to Mexico to work in student outreach. While in Mexico, they saw how many people were migrating to the U.S. and became convicted to move to Chicago's Little Village. Krista is a school teacher in the neighborhood and Pastor Chris is currently leading the congregation at Little Village Karlov. God has blessed the two with a son (Jonathan) and a daughter (Hannah).", LocationPastorName: "Pastor Chris & Krista Ophus", LocationServiceHours: "English 10:00am; Spanish Noon"},
        { LocationCode: "MLR", LocationName: "Melrose Park", LocationNamePrefix: "New Life", LocationPhoneNumber: 7086812948, LocationEmail: "melrose@newlifechicago.org", LocationAddress1: "2001 W. Division St.", LocationCity: "Melrose Park",  LocationState: "IL", LocationZip: 60160, PastorBio: "Pastor John Palmieri made a decision to follow Christ at the age of seventeen and knew that God was calling him into ministry. He graduated from the Moody Bible Institute and completed his Master's Degree in Spiritual Formation and holds a Doctorate from Bakke Graduate University in Transformational Leadership. Over the last 24 years John has served in missions, church planting, live-in discipleship, job training, youth ministry and counseling. He and his wife Christine have three children, Caleb, Hannah and Abbey, and together they are committed to fulfilling God’s purposes in their generation.", LocationPastorName: "Pastor John & Christine Palmieri", LocationServiceHours: "English 10:00; Spanish Noon"},
        { LocationCode: "MDW", LocationName: "Midway", LocationNamePrefix: "New Life", LocationPhoneNumber: 7738389470, LocationEmail: "midway@newlifechicago.org", LocationAddress1: "4101 W. 51st Street", LocationCity: "Chicago",  LocationState: "IL", LocationZip: 60632, PastorBio: "Mark Jobe and his wife Dee have seen New Life grow from a handful of people to thousands meeting at 20 campuses with 36 worship services each weekend. Pastor Mark is the founder of New Life Centers, providing critical support for youth in under-served areas of Chicago. He has been featured in numerous publications and books, and can be heard on his daily radio program, \"Straighttalk\". Recorded broadcasts can be heard at www.pastormarkjobe.com. Mark holds a BA from Columbia International University, an MA from Moody Theological Seminary and a Doctorate from Bakke Graduate University.", LocationPastorName: "Pastor Mark & Dee Jobe", LocationServiceHours: "English 9:30am & 11:30am; Spanish 9:30am & 11:30am"},
        { LocationCode: "MTC", LocationName: "Mont Clare", LocationNamePrefix: "New Life", LocationPhoneNumber: 7736372194, LocationEmail: "montclare@newlifechicago.org", LocationAddress1: "2501 N. Nordica Ave.", LocationCity: "Chicago",  LocationState: "IL", LocationZip: 60607, PastorBio: "Pastor Joshua Holec graduated from New Life’s internship program in 1999. In 2005, he graduated from the Moody Bible Institute with a major in Pastoral Studies. Pastor Joshua was commissioned as Associate Pastor at New Life Melrose in 2001, developing and leading the worship ministry and later the youth ministry. He is a gifted musician, speaker and leader. Joshua and his wife Nancy, also a Moody graduate, have a passion for unlocking the untapped potential in others to live all out for Jesus Christ.", LocationPastorName: "Pastor Joshua & Nancy Holec", LocationServiceHours: "English 9:00am & 11:00am"},
        { LocationCode: "MTG", LocationName: "Montgomery", LocationNamePrefix: "New Life", LocationPhoneNumber: 6308976810, LocationEmail: "montgomery@newlifechicago.org", LocationAddress1: "1144 South Lincoln Avenue", LocationCity: "Montgomery",  LocationState: "IL", LocationZip: 60538, PastorBio: "Pastor John Palmieri made a decision to follow Christ at the age of seventeen and knew that God was calling him into ministry. He graduated from the Moody Bible Institute and completed his Master's Degree in Spiritual Formation and holds a Doctorate from Bakke Graduate University in Transformational Leadership. Over the last 24 years John has served in missions, church planting, live-in discipleship, job training, youth ministry and counseling. He and his wife Christine have three children, Caleb, Hannah and Abbey, and together they are committed to fulfilling God’s purposes in their generation.", LocationPastorName: "Pastor John & Christine Palmieri", LocationServiceHours: "English 10:00"},
        { LocationCode: "OKF", LocationName: "Oak Forest", LocationNamePrefix: "New Life", LocationPhoneNumber: 7085359760, LocationEmail: "oakforest@newlifechicago.org", LocationAddress1: "5333 W. 151st Street", LocationCity: "Oak Forest",  LocationState: "IL", LocationZip: 60452, PastorBio: "Feeling a call to ministry in his teenage years, Andrew preached his first sermon at 16; the same year that he opened his heart to the dream of foreign missions by going on a short term trip to St. Petersburg, Russia. With a focus on intercultural ministry he attended Moody Seminary. He enjoys flirting with his wife Allison and wrestling with his children Levi and Micah. His dream is to see the neglected and outcast find the same hope in Jesus that was offered to him. He currently is serving as Lead Pastor at New Life Oak Forest.", LocationPastorName: "Pastor Andrew & Allison Bierlein", LocationServiceHours: "English 9:30am & 11:00am"},
        { LocationCode: "OKL", LocationName: "Oak Lawn", LocationNamePrefix: "New Life", LocationPhoneNumber: 7086897321, LocationEmail: "oaklawn@newlifechicago.org", LocationAddress1: "9000 S. Ridgeland Ave", LocationCity: "Oak Lawn",  LocationState: "IL", LocationZip: 60453, PastorBio: "Don Kauffman was born and raised in Springfield, IL. He was transformed by Christ when he was 16 years old at a Christ in Youth conference where he immediately heard God’s calling to enter into the ministry. Upon graduating from Lincoln Christian University in 2007 with a degree in Preaching & Biblical Studies he served in ministry in Boulder, CO and Central Illinois. He is currently finishing his Masters in Spiritual Formation at Lincoln Christian University. Don is passionate about life in community and communicating the love of Jesus. While he and his wife Rae have known each other for more than 17 years, they have been married since 2010 and have a son.", LocationPastorName: "Pastor Don & Rae Kauffman", LocationServiceHours: "English 10:00am"},
        { LocationCode: "PTP", LocationName: "Portage Park", LocationNamePrefix: "New Life", LocationPhoneNumber: 7737773360, LocationEmail: "portagepark@newlifechciago.org", LocationAddress1: "5700 W. Berteau Ave.", LocationCity: "Chicago",  LocationState: "IL", LocationZip: 60634, PastorBio: "Asa App grew up in Mexico where his parents are involved in missions work. He met his wife Elizabeth in high school and both of them went on to receive their degrees from Moody Bible Institute. He is currently Lead Pastor at New Life Portage Park and has served on staff since 1993. Pastor Asa is a dynamic pastor with a lot of experience as a youth pastor, raising one of the strongest youth ministries in Chicago. He and his wife have mentored dozens of couples and young leaders. Asa and Elizabeth live on the Northwest side of Chicago and have four children.", LocationPastorName: "Pastor Asa & Elizabeth App", LocationServiceHours: "English 10am and Noon; Spanish 10am"}, 
        { LocationCode: "RGP", LocationName: "Rogers Park", LocationNamePrefix: "New Life", LocationPhoneNumber: 7736456543, LocationEmail: "rogerspark@newlifechciago.org", LocationAddress1: "2424 W. Touhy Ave.", LocationCity: "Chicago", LocationState: "IL", LocationZip: 60645, PastorBio: "Pastor Dwayne and his wife Cecilia have been married for 9 years and have 4 children. They live in the West Rogers Park neighborhood and are excited about being a part of what God is doing throughout the community. Dwayne grew up in the city of Miami and by sixth grade he had been arrested twice. He was quickly headed down the road of juvenile delinquency until he came to Christ at the age of 13. He graduated from Moody Bible Institute and joined the staff at New Life in 1998.", LocationPastorName: "Pastor Dwayne & Ceci Eslick", LocationServiceHours: "English 9:15am & 11:00am; Span translation at 11" },
        { LocationCode: "TRT", LocationName: "Tri-Taylor", LocationNamePrefix: "New Life", LocationPhoneNumber: 7732940418, LocationEmail: "tritaylor@newlifechicago.org", LocationAddress1: "2130 W. Ogden Ave.", LocationCity: "Chicago", LocationState: "IL", LocationZip: 60612, PastorBio: "Danny Lopez is a native of Chicago and grew up in Humboldt Park, in a home where drugs, alcohol, gang activity and witchcraft was prevalent. At the age of 13 God's grace changed the course of his life. He graduated from Moody Bible Institute with a degree in Bible Theology and is well known in the city for his 25 years of youth ministry to the teens in churches and the local high schools. Danny is married to Cyrene and they have three grown children who are serving the Lord and active in various areas of ministry. Danny is the Teaching Pastor at the New Life Tri-Taylor Campus at Hope Academy and is a dynamic speaker who is passionate about Jesus. ", LocationPastorName: "Pastor Danny & Cyrene Lopez", LocationServiceHours: "English 10:00am" },
        { LocationCode: "LKV", LocationName: "West Lakeview", LocationNamePrefix: "New Life", LocationPhoneNumber: 7733880637, LocationEmail: "westlakeview@newlifechicago.org", LocationAddress1: "2958 N. Damen Ave.", LocationCity: "Chicago", LocationState: "IL", LocationZip: 60618, PastorBio: "Kevin & Gillian moved to Chicago in 1995 and New Life West Lakeview became their home location in December of 2001, shortly after the location was restarted. Kevin began serving as the location pastor for New Life West Lakeview in 2004. He and Gillian have five children. Kevin works with New Life church plants on the north side and strategizes about starting movement churches in new cities. He is passionate about seeing new leaders raised up and forging bonds between pastors citywide. Raised in the suburbs of Grand Rapids, MI, God has given both Kevin & Gillian a heart and passion for the city.", LocationPastorName: "Pastor Kevin & Gillian Bruursema", LocationServiceHours: "English 9:00am & 11:00am" }
    ];
};


angular.module('ng').filter('tel', function () {
    return function (tel) {
        if (!tel) { return ''; }

        var value = tel.toString().trim().replace(/^\+/, '');

        if (value.match(/[^0-9]/)) {
            return tel;
        }

        var country, city, number;

        switch (value.length) {
            case 10: // +1PPP####### -> C (PPP) ###-####
                country = 1;
                city = value.slice(0, 3);
                number = value.slice(3);
                break;

            case 11: // +CPPP####### -> CCC (PP) ###-####
                country = value[0];
                city = value.slice(1, 4);
                number = value.slice(4);
                break;

            case 12: // +CCCPP####### -> CCC (PP) ###-####
                country = value.slice(0, 3);
                city = value.slice(3, 5);
                number = value.slice(5);
                break;

            default:
                return tel;
        }

        if (country == 1) {
            country = "";
        }

        number = number.slice(0, 3) + '-' + number.slice(3);

        return (country + " (" + city + ") " + number).trim();
    };
});